name: Frontend CI

on:
  push:
    paths:
      - frontend/**
      - .github/workflows/frontend-ci.yml

defaults:
  run:
    working-directory: frontend

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2 # Use the version pinned by volta
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Lint style
        run: npm run lint:style

      - name: Format
        run: npm run format

      - name: Build
        run: npm run build
